### ISSUE TITLE
REL: v0.4.0

### ISSUE THREAD

**Issue by sinhrks** [pandas-ml/pandas-ml#80]
- [x] Compat/test for sklearn 0.18.0 (#81)
  - [x] initial fix (#81)
  - [x] wrapper for cross validation classes (re-enable skipped tests) (#85)
  - [x] tests for multioutput (#86)
  - [x] Update doc
- [x] Compat/test for pandas 0.19.0 (#83)
- [x] Update release note (#88)

**Comment by sinhrks** [comment]
I think it's ready. Let me release once @scls19fr reviews #87.

**Comment by scls19fr** [comment]
I think we need to be sure that https://github.com/pandas-ml/pandas-ml/issues/70 can be closed before releasing. See https://github.com/pandas-ml/pandas_confusion/issues/15
Except this... I think that's ok for release!
Thanks for the great work.

**Comment by sinhrks** [comment]
I think #70 includes the same fix. can u check?

**Comment by scls19fr** [comment]
it seems good.
